### ISSUE TITLE
Cannot jump to the content of the search by clicking the results

### ISSUE THREAD

**Issue by Michael728** [docsifyjs/docsify#1090]
env:
```shell
docsify-cli version:
  4.4.0
```

problem: I create a page: https://awesome-wiki.github.io/awesome-wiki-bookmarks/#/ ,when I type `Linux` in the search placeholder, It can show the results of search, I click the reulst, it can't jump to the content! 

PS: not every result cannot jump by clicking

**Comment by anikethsaha** [comment]
its working fine with our docs. Can you create a reproducible sandbox for this.

**Comment by Michael728** [comment]
the repo url is https://github.com/awesome-wiki/awesome-wiki-bookmarks

**Comment by anikethsaha** [comment]
I am asking for the sandbox or repo so that I can take a look cause its working fine in our docs site.


Also, you did fill the issue template.we have written in clear in the template that we will close the issue if it's not there. That template is important and helps us in investigating the matter quickly.

**Comment by mouchar** [comment]
@anikethsaha,  navigating to search results does not work reliably even on your docs site (https://docsify.js.org/).
I tried in Chrome 81 and Firefox 75.0

Simple test scenario:
* Go to https://docsify.js.org/
* Click to the search box, fill in some work with a lot of results (I used `github`)
* Click on random results and carefully watch what happens.

Many links work as expected, some navigate to the wrong location (correct page, wrong anchor) and some simply do nothing.

I think the issue often occurs when trying to navigate to another anchor on the same page.

**Comment by anikethsaha** [comment]
> Many links work as expected, some navigate to the wrong location (correct page, wrong anchor) and some simply do nothing.

> I think the issue often occurs when trying to navigate to another anchor on the same page.

its working as expected. 

> * Click to the search box, fill in some work with a lot of results (I used `github`)
> * Click on random results and carefully watch what happens.

I typed github and clicked every link visible in it, working as expected. Maybe I am missing something.

**Comment by jjallaire** [comment]
I am seeing this same behavior both locally as well as on the docsify-themeable website. Here's what I see:

![docsify-search](https://user-images.githubusercontent.com/104391/82751139-4446f900-9d83-11ea-9be4-7a134653e0bb.gif)

Note that the URL changes to include `id=emoji` but the page doesn't navigate to the emjoi section.

**Comment by sy-records** [comment]
@jjallaire The next version should be fixed. #1190

**Comment by jjallaire** [comment]
Excellent! I was speculating that this might also have something to do w/ async image loading (as I have a number of screenshots on the page): https://gitmemory.com/issue/docsifyjs/docsify/624/489617399

**Comment by jjallaire** [comment]
Is there a straightforward way to run the new version on my site prior to it's release?

**Comment by sy-records** [comment]
> Is there a straightforward way to run the new version on my site prior to its release?

You can try to load these two js files.
```javascript
<script src="//cdn.jsdelivr.net/gh/sy-records/staticfile@master/js/docsify/docsify.min.js"></script>

<script src="//cdn.jsdelivr.net/gh/sy-records/staticfile@master/js/docsify/search.min.js"></script>
```

**Comment by jjallaire** [comment]
That works great, thank you!!!!!

**Comment by sy-records** [comment]
fixed via #1175. If there are still questions, you can reopen the issue.

**Comment by yash-bst** [comment]
This issue is still happening.

- Searched for "B".
- Results show "AB" and "BC" which are from the same page but different sections.
- I select either one of the choices but it doesn't fully jump to those sections.

I also suspect it is related to lazy loading of images since if I repeatedly select "AB" then "BC" then "AB" and so on. After a couple seconds it starts jumping properly.
