### ISSUE TITLE
links not working properly for quoted headings

### ISSUE THREAD

**Issue by yogitheboss** [docsifyjs/docsify#1965]
#### Steps to reproduce
create a navigation list using 
- [heading](#link1_heading)
- [heading](#link2_heading)
 if we create a heading 
"link1_heading"
"link2_heading"
the links doesn't work in docsify generated webpage as the id attribute is "quotlink1_headingquot" 

#### What is current behaviour
the links doesn't work if quotation is included in the name , as id generated of the heading is quot_id_quot instead of quot .

#### What is the expected behavior
the links should work fine as the readme file treats quotes and no quotes the same

#### Other relevant information
this bug is causing the https://p5js.org/contributor-docs/#/./contributor_guidelines page's some links to not work
eg. "found a bug" , "Existing Feature Enhancement" etc.
[New Feature Request](https://p5js.org/contributor-docs/#/./contributor_guidelines?id=new-feature-request)
[Discussion](https://p5js.org/contributor-docs/#/./contributor_guidelines?id=discussion)"

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: windows 10
- Node.js version: v16.13.2. 
- npm/yarn version: v8.3.2
- Browser version:  v109.0.5414.75
- Docsify version: 4.4.4
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-joana-43qgnd?file=/README.md)

**Comment by Koooooo-7** [comment]
Hi @yogitheboss , IIRC,  It has been fixed, plz update the docsify  version `https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js`  to have a try.

**Comment by yogitheboss** [comment]
@Koooooo-7 , I checked again but still the problem persists . I am using latest version of docsify but still the links aren't working. 
the data id of element(headings) are still quot_name_quot instead of name because of which links aren't working.

**Comment by yogitheboss** [comment]
I think I have got my answer , Thanks for responding @Koooooo-7  I am closing the issue

**Comment by yogitheboss** [comment]
@Koooooo-7  the custom id is working with docsify but markdown renderer isn't rendering it properly
