### ISSUE TITLE
The 'undefined' word appears sometime

### ISSUE THREAD

**Issue by Yan-AM** [docsifyjs/docsify#571]
Hi,

I'm using version 4.7.0.

Sometime the word 'undefined' appear if it's the first time I'm going on the page.

The text is hidden when I refresh the page.

See picture :
![issue_undefined](https://user-images.githubusercontent.com/41004332/42451357-45174e10-8387-11e8-9b73-82ef59e334fc.png)

Tested on FireFox 61.0.1.

Thank-you for your Docsify !
Yan

**Comment by QingWei-Li** [comment]
Can you please provide an example?

**Comment by Yan-AM** [comment]
Yes, this is the 'readme' file where I'have the problem :

```markdown
# Documentations de nos applications locales

[filename](../applications/alias/doc/readme.md ':include')
* [Documentation utilisateur](http://localdomain.fr/applications/alias/#/utilisateur/readme)
* [Documentation technique](http://localdomain.fr/applications/alias/#/technique/readme)


[filename](../applications/api/doc/readme.md ':include')
* [Documentation utilisateur](http://localdomain.fr/applications/api/#/utilisateur/readme)
* [Documentation technique](http://localdomain.fr/applications/api/#/technique/readme)


[filename](../applications/sec/doc/readme.md ':include')
* [Documentation utilisateur](http://localdomain.fr/applications/secAuto/#/utilisateur/readme)
* [Documentation technique](http://localdomain.fr/applications/secAuto/#/technique/readme)


[filename](../applications/secAuto/doc/readme.md ':include')
* [Documentation technique](http://localdomain.fr/applications/secAutoAutoConfig/#/technique/readme)

## Concernant cette documentation
* [Documentation technique](http://localdomain.fr/applications/documentation/#/technique/readme)
```

And here, is the config in my pape :
```javascript
<script>
		window.$docsify = {

			name: 'Accueil des applications',
			nameLink: 'http://localdomain.fr',

			homepage: 'readme.md',
			basePath: 'doc/',
			externalLinkTarget: '_self', // Par défaut '_blank'.

			search: {
				maxAge: 60,
				placeholder: 'Recherche',
				noData: 'Aucun résultat'
			}
			plugins: [
				function (hook) {
				  var footer = [
					'<hr style="padding-top: 30px;" />',
					'<footer>',
					'<strong>Documentation</strong>',
					'</footer>'
				  ].join('')

				  hook.afterEach(function (html) {
					return html + footer
				  })
				}
			]
		}
</script>
```
Thanks,
Yan

**Comment by extrapixel** [comment]
I experience the same - we have a similar setup. 
Sometimes, instead of "undefined", it's "filename". An URL where this happens usually:
https://www.whiteboxes.ch/docs/tentacle/t1/#/protocols

It takes 2-3 reloads sometimes to load all includes.

**Comment by QingWei-Li** [comment]
@extrapixel fixed in `v4.8.2`

**Comment by extrapixel** [comment]
@QingWei-Li yeah, seems fixed. @Yan-AM ?

**Comment by extrapixel** [comment]
> @QingWei-Li yeah, seems fixed. @Yan-AM ?

Actually, it still does not work. A "filename" link appears instead of the include. 1-2 reloads will fix it.

**Comment by chrisschaub** [comment]
Yeah, experiencing same thing on 4.7.1 and latest.

**Comment by cheng-kang** [comment]
Been trying to reproduce but all seems fine locally. @extrapixel https://github.com/whitebox-labs/whitebox-docs/blob/master/tentacle/t1 this works locally as well.

Could anyone please setup a project that can reproduce this issue?

**Comment by extrapixel** [comment]
> Could anyone please setup a project that can reproduce this issue?

clicking the link (https://www.whiteboxes.ch/docs/tentacle/t1/#/protocols) will reproduce the issue. What do you mean by "locally"? The includes are loaded from external sources (GitHub):

`basePath: 'https://raw.githubusercontent.com/whitebox-labs/whitebox-docs/master/tentacle/t1/',`

and the links in the markdown are relative:
(I guess this is similar to @Yan-AM 's setup. @chrisschaub what about your links - relative? )

`[filename](../common/ezo-protocols.md ':include')`

resolving to this path (outside the base-path).

`https://raw.githubusercontent.com/whitebox-labs/whitebox-docs/master/tentacle/common/ezo-protocols.md`

**Comment by extrapixel** [comment]
this issue is still open. @cheng-kang

**Comment by extrapixel** [comment]
almost 2 years and this bug is still there

**Comment by anikethsaha** [comment]
@extrapixel can you share a reproducible sandbox for this using the latest version. 
it would help a lot in investigating this.

Sorry for this much delayed, this might have missed my eyes

**Comment by slhck** [comment]
I got it whenever I add an external link to my page.

```
http://example.com
```

rendered as `undefined`. Turns out I was using an empty link function that I forgot to override:

```html
<script>
  window.$docsify = {
    name: "Example",
    repo: "",
    markdown: {
      smartypants: true,
      // renderer: {
      //   link: function () {
      //     // ...
      //   },
      // },
    },
  };
</script>
```

Once commented out (as above) it works.
